# GitHub Pages 部署工作流
name: Deploy CATIA B30 Documentation to Pages

on:
  # 当推送到 main 分支时触发
  push:
    branches: ["main"]
  
  # 允许手动运行工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建作业
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Pages
        uses: actions/configure-pages@v4
      
      - name: 上传构件
        uses: actions/upload-pages-artifact@v3
        with:
          # 上传 B30_htmls 目录
          path: './B30_htmls'
  
  # 部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4